import type { Metadata } from "next";
import { Asap } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Home/Navbar";
import { Toaster } from "sonner";
import Footer from "@/components/Home/Footer";

const inter = Asap({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <NavBar />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
